#!/bin/bash

FILE="/home/pranav/Downloads/vulf.ovpn"
OUT_FILE="/home/pranav/.htbtun_out"

openvpn $FILE > $OUT_FILE &
sleep 8
BOOL=$(grep 'ERROR' $OUT_FILE)
# echo $BOOL
if [[ "$BOOL" ]]; then
    echo "Could not connect to HTB"
    echo "Log file: $HOME/.htbtun_out"
else
    echo "Connected"
fi




