#!/bin/bash

BGICO="^b#2b2b2b^"
BGVAL=""
FG="^c#ffffff^"
SCM_NORM="^d^"
BATFULL=""
BAT70=""
BAT50=""
BAT20=""
BATCRTCL=""
BATCHARGE=""
BAT=$(cat /sys/class/power_supply/BAT1/capacity)
STATUS=$(cat /sys/class/power_supply/BAT1/status)

if [ $STATUS = "Charging" ]
then
    echo -e "$FG$BGICO $BATCHARGE $SCM_NORM $BAT"
elif [ $BAT -ge "90" ]
then
    echo -e "$FG$BGICO $BATFULL $SCM_NORM $BAT"
elif [ $BAT -lt "90" -a $BAT -ge "70" ]
then
    echo -e "$FG$BGICO $BAT70 $SCM_NORM $BAT"
elif [ $BAT -lt "70" -a $BAT -ge "50" ]
then
    echo -e "$FG$BGICO $BAT50 $SCM_NORM $BAT"
elif [ $BAT -lt "50" -a $BAT -ge "20" ]
then
    echo -e "$FG$BGICO $BAT20 $SCM_NORM $BAT"
    if [ $BAT -eq "49" -o $BAT -eq "40" -o $BAT -eq "30" ]
    then
        notify-send -t 10000 "Get ready to plug in the power adapter"
    fi
elif [ $BAT -lt "20" ]
then
    echo -e "$FG$BGICO $BATCRTCL $SCM_NORM $BAT"
    if [ $BAT -eq "19" -o $BAT -eq "15" -o $BAT -eq "10" ]
    then
        notify-send -u critical -t 10000 "Battery low, Plug in!"
    fi
fi
