#! /bin/bash

BGICO="^b#8c8c8c^"
BGVAL=""
FG="^c#ffffff^"
SCM_NORM="^d^"

CAL=""
DATE=$(date +"%a, %d %b" | tr '[:upper:]' '[:lower:]')

#echo -e "$FG$BGICO $CAL $SCM_NORM $DATE"
echo -e " $CAL $FG$BGICO $DATE $SCM_NORM"
