#! /bin/bash

BGICO="^b#000000^"
BGVAL=""
FG="^c#ffffff^"
SCM_NORM="^d^"

VOLNORM=""
VOLMUTE=""
VOLUME=$(pactl list sinks | grep Volume | head -n1 | awk '{print $5}')
MUTE=$(pactl list sinks | grep Mute | cut -d ':' -f 2 | sed 's/^ * //g')

if [ $MUTE == "yes" ]
then
    echo -e "$FG$BGICO $VOLMUTE $SCM_NORM muted"
else
    echo -e "$FG$BGICO $VOLNORM $SCM_NORM $VOLUME"
fi
