#! /bin/bash

BGICO="^b#295890^"
BGVAL="^b#007CC3^"
FG="^c#ffffff^"
SCM_NORM="^d^"

VOLNORM=""
VOLMUTE=""
VOLUME=$(pactl list sinks | grep Volume | head -n1 | awk '{print $5}')
MUTE=$(pactl list sinks | grep Mute | cut -d ':' -f 2 | sed 's/^ * //g')

if [ $MUTE == "yes" ]
then
    echo -e "$FG$BGICO $VOLMUTE $SCM_NORM"
else
    echo -e "$FG$BGICO $VOLNORM $BGVAL $VOLUME $SCM_NORM"
fi
